
# the following code make the list of properties / methods
use application "polytope";
include "common::sage.rules";

print "# This file was autogenerated! Do not edit!!!\n\n";

# Polytope<Rational>
my $c = cube(3);
my $r = Sage::properties_for_object($c);
print "type_properties[b\"".$c->type->full_name."\"] = {\n";
foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
print "}\n";

# Graph<Undirected>
$c = cube(3)->DUAL_GRAPH;
$r = Sage::properties_for_object($c);
print "type_properties[b\"".$c->type->full_name."\"] = {\n";
foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
print "}\n";

# GeometricSimplicialComplex<Rational>
$c = cube(3)->TRIANGULATION;
$r = Sage::properties_for_object($c);
print "type_properties[b\"".$c->type->full_name."\"] = {\n";
foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
print "}\n";

# EdgeWeightedGraph
$c = cube(3)->TRIANGULATION->MIXED_GRAPH;
$r = Sage::properties_for_object($c);
print "type_properties[b\"".$c->type->full_name."\"] = {\n";
foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
print "}\n";


# Lattice<BasicDecoration, Sequential>
$c = cube(3)->HASSE_DIAGRAM;
$r = Sage::properties_for_object($c);
print "type_properties[b\"".$c->type->full_name."\"] = {\n";
foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
print "}\n";

#$c = cube(3)->GROEBNER_BASIS;
#$r = Sage::properties_for_object($c);
#print "type_properties[b\"".$c->type->full_name."\"] = {\n";
#foreach (keys %$r) {print "    b\"".$_."\" : b\"".$r->{$_}."\",\n"};
#print "}\n";

